sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t ashevade/react-test -f ./client/Dockerfile.dev ./client
scripts:
    - docker run -e CI=true ashevade/react-test npm test 

after-success:
    - docker build -t ashevade/multi-client ./client
    - docker build -t ashevade/multi-nginx ./nginx
    - docker build -t ashevade/multi-server ./server
    - docker build -t ashevade/multi-worker ./worker
    #Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #- docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD" docker.io

    #push the images
    - docker push ashevade/multi-client
    - docker push ashevade/multi-nginx
    - docker push ashevade/multi-server
    - docker push ashevade/multi-worker








